apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: medez/ecomm-cart:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: global-configuration
                key: POSTGRES_URL
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: global-configuration
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: global-configuration
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: global-configuration
                key: POSTGRES_USER
        

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: test
spec:
  selector:
    app: cart
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082