apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: cart
          image: medez/ecomm-cart:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: global-configuration
                  key: POSTGRES_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: global-configuration
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: global-configuration
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: global-configuration
                  key: POSTGRES_USER

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: test
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
